const test = require("node:test");
const assert = require("node:assert/strict");
const AdmZip = require("adm-zip");

const { selectPreferredFinalMessage } = require("../lib/file-utils");
const { extractZipAttachmentExcerpt, formatJiraApiError } = require("../lib/core/jira-api");
const { parseNamedSections, parseRcaFields } = require("../lib/parsing");
const { buildSessionPrompt, formatJiraEvidenceForPrompt, normalizeRequest } = require("../lib/prompts");
const { evaluateRcaOutput } = require("../lib/rca-output");
const { currentArtifacts } = require("../lib/core/session-store");
const { addGenericJiraMcpAliases, resolveTicketScopedMcpServers } = require("../lib/core/ticket-routing");

test("normalizeRequest strips placeholder issue titles generated by the UI", () => {
  const request = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "FPS-135835",
    issueTitle: "Jira FPS-135835 RCA",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });

  assert.equal(request.issueTitle, "");
});

test("buildSessionPrompt tells Codex how to anchor the real bug title when the operator did not provide one", () => {
  const request = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "FPS-135835",
    issueTitle: "Jira FPS-135835 RCA",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });

  const prompt = buildSessionPrompt(request, null);
  assert.match(prompt, /Fetch the exact bug title from Jira when available, or use the operator-provided title/i);
  assert.match(prompt, /If no live ticket system is available, state that the exact bug title was not retrievable/i);
  assert.match(prompt, /Do not return a generic Oracle Restaurants overview or broad subsystem guess/i);
});

test("normalizeRequest infers Jira source from Jira-style keys and BugDB for numeric ids", () => {
  const jiraRequest = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "FPS-135835",
    issueTitle: "",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });
  const bugdbRequest = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "39090104",
    issueTitle: "",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });

  assert.equal(jiraRequest.ticketSource, "jira");
  assert.equal(bugdbRequest.ticketSource, "bugdb");
});

test("buildSessionPrompt uses prefetched Jira REST evidence for Jira tickets and packaged references for BugDB", () => {
  const jiraRequest = {
    ...normalizeRequest({
      product: "simphony",
      workspace: "shared://simphony",
      ticketId: "FPS-135835",
      issueTitle: "",
      extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
    }),
    jiraEvidence: {
      key: "FPS-135835",
      summary: "Ticket summary from Jira",
      description: "Observed behavior from direct Jira API.",
      comments: [{ author: "Ayush", created: "2026-05-05", body: "First comment" }],
      attachments: [{ filename: "error.log", mimeType: "text/plain", size: 120, excerpt: "stack trace" }]
    }
  };
  const bugdbRequest = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "FPS-135835",
    issueTitle: "",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });
  bugdbRequest.ticketId = "39090104";
  bugdbRequest.ticketSource = "bugdb";

  const jiraPrompt = buildSessionPrompt(jiraRequest, null);
  const bugdbPrompt = buildSessionPrompt(bugdbRequest, null);

  assert.match(jiraPrompt, /Use the prefetched Jira REST API evidence in this prompt as the required factual Jira source/i);
  assert.match(jiraPrompt, /Do not try Jira MCP in this run/i);
  assert.match(jiraPrompt, /Prefetched Jira Evidence:/i);
  assert.match(jiraPrompt, /Ticket summary from Jira/i);
  assert.match(bugdbPrompt, /This ticket is BugDB-backed\. Use the packaged references folder as the BugDB workflow path/i);
  assert.match(bugdbPrompt, /Do not use Jira MCP as BugDB evidence/i);
});

test("buildSessionPrompt steers Jira-backed runs toward Jira-evidenced Simphony files before broad searches", () => {
  const request = {
    ...normalizeRequest({
      product: "developer-workspace",
      workspace: "C:\\Simphony\\trunk\\19.7.4",
      ticketId: "FPS-121587",
      issueTitle: "",
      extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
    }),
    jiraEvidence: {
      key: "FPS-121587",
      summary: "When Printing a Seat Check Discounts are not showing up on print",
      description: "Seat checks and check journal miss automatic item discount lines.",
      comments: [{
        author: "Rishabh",
        created: "2026-04-28",
        body: "**RCA Analysis** Seat-check formatting and journal ordering are involved."
      }],
      attachments: [{
        filename: "FPS-121587.patch",
        mimeType: "text/plain",
        size: 1960,
        excerpt: [
          "Index: OPS/Ops/CommandHandlers/TenderMedia.cs",
          "Index: PosCore.Check.Operations/Discount/AutomaticDiscountHelper.cs"
        ].join("\n")
      }]
    }
  };

  const prompt = buildSessionPrompt(request, null);

  assert.match(prompt, /The UI product label is `developer-workspace`/i);
  assert.match(prompt, /The Jira evidence points to a Simphony OPS printing and discount code path/i);
  assert.match(prompt, /Start with these Jira-evidenced files before widening the search/i);
  assert.match(prompt, /OPS\/Ops\/CommandHandlers\/TenderMedia\.cs/i);
  assert.match(prompt, /PosCore\.Check\.Operations\/Discount\/AutomaticDiscountHelper\.cs/i);
  assert.match(prompt, /Do not begin with repo-wide searches for the ticket key, the literal UI product label, or generic workspace terms/i);
});

test("formatJiraEvidenceForPrompt formats Jira fields comments and attachments", () => {
  const formatted = formatJiraEvidenceForPrompt({
    key: "FPS-135835",
    summary: "Ticket summary from Jira",
    description: "Observed behavior from direct Jira API.",
    status: "Open",
    comments: [{ author: "Ayush", created: "2026-05-05", body: "First comment" }],
    attachments: [{ filename: "error.log", mimeType: "text/plain", size: 120, excerpt: "stack trace" }]
  });

  assert.match(formatted, /Ticket key: FPS-135835/);
  assert.match(formatted, /Comments:/);
  assert.match(formatted, /error\.log/);
});

test("Jira 401 JSON errors are converted to plain English", () => {
  const message = formatJiraApiError({
    statusCode: 401,
    body: Buffer.from(JSON.stringify({
      errorMessages: ["You are not authenticated."],
      errors: {}
    }))
  }, "Failed to fetch Jira issue FPS-135835.");

  assert.equal(
    message,
    "Jira authentication failed. The Jira token may be expired or invalid. Update the Jira personal access token and try again."
  );
  assert.doesNotMatch(message, /^\{/);
});

test("extractZipAttachmentExcerpt reads text files inside an in-memory zip attachment", () => {
  const zip = new AdmZip();
  zip.addFile("logs/error.log", Buffer.from("stack trace line", "utf8"));
  zip.addFile("src/Foo.cs", Buffer.from("public class Foo {}", "utf8"));
  zip.addFile("bin/image.png", Buffer.from([0, 1, 2, 3]));

  const excerpt = extractZipAttachmentExcerpt(zip.toBuffer(), "evidence.zip");

  assert.match(excerpt, /evidence\.zip \/ logs\/error\.log/);
  assert.match(excerpt, /stack trace line/);
  assert.match(excerpt, /evidence\.zip \/ src\/Foo\.cs/);
  assert.match(excerpt, /public class Foo/);
  assert.doesNotMatch(excerpt, /image\.png/);
});

test("resolveTicketScopedMcpServers requires Jira MCP for Jira and suppresses it for BugDB", () => {
  const jiraSelection = resolveTicketScopedMcpServers({
    ticketSource: "jira",
    ticketId: "FPS-135835"
  }, {
    runnableUrlServers: [],
    runnableCommandServers: [],
    skippedServers: [{
      name: "mcp-atlassian-gbujira",
      command: "docker",
      args: ["run", "ghcr.io/sooperset/mcp-atlassian:latest"],
      env: { JIRA_URL: "https://gbujira.oraclecorp.com/" },
      probe: { ok: false, reason: "Docker daemon is unavailable." }
    }]
  });
  const bugdbSelection = resolveTicketScopedMcpServers({
    ticketSource: "bugdb",
    ticketId: "39090104"
  }, {
    runnableUrlServers: [],
    runnableCommandServers: [{
      name: "mcp-atlassian-gbujira",
      command: "docker",
      args: ["run", "ghcr.io/sooperset/mcp-atlassian:latest"],
      env: { JIRA_URL: "https://gbujira.oraclecorp.com/" },
      probe: { ok: true, reason: "" }
    }],
    skippedServers: []
  });

  assert.match(jiraSelection.blockingIssue, /Jira RCA requires a runnable Jira MCP server/i);
  assert.equal(bugdbSelection.blockingIssue, "");
  assert.equal(bugdbSelection.runnableCommandServers.length, 0);
});

test("addGenericJiraMcpAliases maps a single configured Jira server to the generic jira name", () => {
  const aliasedServers = addGenericJiraMcpAliases([{
    kind: "command",
    name: "mcp-atlassian-gbujira",
    command: "docker",
    args: ["run", "ghcr.io/sooperset/mcp-atlassian:latest"],
    env: { JIRA_URL: "https://gbujira.oraclecorp.com/" }
  }]);

  assert.equal(aliasedServers.length, 2);
  assert.equal(aliasedServers[1].name, "jira");
  assert.equal(aliasedServers[1].command, "docker");
});

test("evaluateRcaOutput rejects generic low-confidence RCA text", () => {
  const request = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "FPS-135835",
    issueTitle: "",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });
  const finalMessage = [
    "Plan",
    "- Review the generic subsystem.",
    "",
    "MCP Calls",
    "- None",
    "",
    "Result Summary",
    "Low confidence generic guidance for the selected Oracle Restaurants product.",
    "",
    "## RCA: FPS-135835",
    "Confidence",
    "Low confidence",
    "",
    "Remaining Uncertainty",
    "Not enough evidence."
  ].join("\n");
  const sections = parseNamedSections(finalMessage);
  const rcaFields = parseRcaFields(sections.RCA);

  const evaluation = evaluateRcaOutput({ request, sections, rcaFields, finalMessage });

  assert.equal(evaluation.shouldReject, true);
  assert.match(evaluation.reasons.join("\n"), /generic product guidance|ticket-specific evidence/i);
});

test("evaluateRcaOutput accepts anchored RCA text with evidence and root cause fields", () => {
  const request = normalizeRequest({
    product: "simphony",
    workspace: "shared://simphony",
    ticketId: "FPS-135835",
    issueTitle: "Check analysis ignores exact bug symptom and returns unrelated RCA",
    extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
  });
  const finalMessage = [
    "Plan",
    "- Fetch FPS-135835 details and inspect the mapped RCA path.",
    "",
    "MCP Calls",
    "- bugdb.getBug(FPS-135835)",
    "",
    "Result Summary",
    "FPS-135835 stays anchored to the requested symptom and the failure is in the RCA prompt shaping path.",
    "",
    "## RCA: FPS-135835",
    "Comments",
    "The bug says the RCA answer is low confidence and unrelated to the requested issue.",
    "",
    "Log Evidence",
    "The request reached the server with a placeholder issue title of Jira FPS-135835 RCA.",
    "",
    "Subsystem",
    "RCA prompt shaping",
    "",
    "Culprit",
    "normalizeRequest accepted the placeholder issue title and passed it into the RCA prompt.",
    "",
    "Why It Fails",
    "The model starts from a synthetic issue title instead of the real bug title, so the answer drifts.",
    "",
    "Complete Fix",
    "Strip placeholder titles, fetch the real bug title first, and reject generic low-confidence RCA output.",
    "",
    "Confidence",
    "High",
    "",
    "Remaining Uncertainty",
    "None in the prompt path."
  ].join("\n");
  const sections = parseNamedSections(finalMessage);
  const rcaFields = parseRcaFields(sections.RCA);

  const evaluation = evaluateRcaOutput({ request, sections, rcaFields, finalMessage });

  assert.equal(evaluation.shouldReject, false);
});

test("evaluateRcaOutput rejects Jira MCP blocker text when Jira REST evidence was already prefetched", () => {
  const request = {
    ...normalizeRequest({
      product: "simphony",
      workspace: "shared://simphony",
      ticketId: "FPS-121587",
      issueTitle: "When Printing a Seat Check Discounts are not showing up on print",
      extraInstructions: "Keep the RCA specific to the selected Jira/BugDB ticket, its exact symptom, and the selected Oracle Restaurants product. Do not drift into generic product guidance."
    }),
    jiraEvidence: {
      key: "FPS-121587",
      summary: "When Printing a Seat Check Discounts are not showing up on print",
      comments: [{ author: "Ayush", created: "2026-05-05", body: "Direct Jira REST evidence is present." }]
    }
  };
  const finalMessage = [
    "Plan",
    "- Query Jira details.",
    "",
    "MCP Calls",
    "- None",
    "",
    "Result Summary",
    "Status: Blocked on Jira MCP. Exact bug title and ticket-specific evidence for FPS-121587 were not retrievable.",
    "",
    "## RCA: FPS-121587",
    "Comments",
    "Jira MCP unavailable.",
    "",
    "Confidence",
    "Low",
    "",
    "Remaining Uncertainty",
    "High because Jira MCP is unavailable."
  ].join("\n");
  const sections = parseNamedSections(finalMessage);
  const rcaFields = parseRcaFields(sections.RCA);

  const evaluation = evaluateRcaOutput({ request, sections, rcaFields, finalMessage });

  assert.equal(evaluation.shouldReject, true);
  assert.match(evaluation.reasons.join("\n"), /Jira MCP blocker even though prefetched Jira REST evidence/i);
});

test("selectPreferredFinalMessage drops transient Codex startup noise when no RCA output exists", () => {
  const finalMessage = selectPreferredFinalMessage({
    finalMessage: "",
    liveText: "",
    stderrText: "Reading prompt from stdin...",
    fallbackFailureMessage: "",
    code: 1
  });

  assert.equal(finalMessage, "");
});

test("currentArtifacts tolerates null owner users for unauthenticated health checks", () => {
  const artifacts = currentArtifacts(null);

  assert.equal(typeof artifacts, "object");
  assert.deepEqual(Object.keys(artifacts).sort(), ["aiToolInstruction", "error", "newToolInstruction"]);
});
